### ISSUE TITLE
ExtensionManager still asks for installing dependency WindowLevelEffect

### ISSUE THREAD

**Issue by che85** [fedorov/PCampReview#142]
I removed the dependency from the code, but it doesn't have any effect. Maybe there is something cached in the ExtensionManager?

**Comment by che85** [comment]
@fedorov Do you have any idea, why that happens?

**Comment by fedorov** [comment]
Interesting - I am actually not sure why it works at all, since it does not list dependencies in the makefile as should be done (see example here: https://github.com/SlicerProstate/SliceTracker/blob/master/CMakeLists.txt#L13). It does list WindowLevelEffect in ext4 (https://github.com/Slicer/ExtensionsIndex/blob/master/mpReview.s4ext#L15), but I thought that one has no meaning, and only cmakelists one is considered. How about you add the correct dependencies to cmakelists, and I will update s4ext?
